### ISSUE TITLE
"HttpRequest" in "httpListener.HttpRequest.Subscribe()" is not defined

### ISSUE THREAD

**Issue by paulyfwu** [1iveowl/Simple-Http-Listener-PCL#1]
Dear 1iveowl: 
I encountered two issues with the below quoted example "private async Task StartListener()" from your post :

000) I had to search your src code, and find the proper namespace to use, as "using SimpleHttpServer.Service;"

AAA)             "Start()" method is not defined, and I had to change it to ===>
await httpListener.StartTcpRequestListener(port: 8000);

BBB) the "HttpRequest" in "httpListener.HttpRequest.Subscribe()" is not defined. I am stuck.
Thanks. Paul

ps: if there could be a complete simple example of how to "//Enter your code handling each incoming Http request here.", such as returning a simple echo or current time, that would be great.

==================================
private async Task StartListener()
{
    var httpListener = new HttpListener(timeout:TimeSpan.FromSeconds(30));
AAA    await httpListener.Start(port:8000);

    // Rx Subscribe
BBB    httpListener.HttpRequest.Subscribe(
       request =>
       {
           //Enter your code handling each incoming Http request here.
       });
}

**Comment by 1iveowl** [comment]
Thank you paulyfwu. 

You're absolutely right. What a mess. I had updated the code but forgot to update the example. This is done now. I hope the examples are more clear?

**Comment by paulyfwu** [comment]
Thanks 1iveowl, for the very timely updates, highly appreciated :-)

Pardon some further nagging on the issue below:

After removing a reference conflict on "System.Runtime.InteropServices.WindowsRuntime.dll" (Error) and still a remaining version 3.0.0 versus 2.2.5 conflict on "System.Reactive.Linq.dll" (Warning only), 
[Note that these two new references were added when I performed "PM> Install-Package SimpleHttpListener"]

Now I can build on VS2015 and deploy it to an HTC phone on Android 4.4.2 and run testing.

But the call to
"await httpListener.StartTcpRequestListener(port: 8000);"
 appears to never complete or return.

One good thing is of course that it did not crash or anything... but the listener is not functioning as expected.
Is this problem stemming from the remaining reference conflicts, or is it due to dependency on Android permissions/capabilities that need to be set separately outside of the program/App? Thanks again, Paul

**Comment by 1iveowl** [comment]
You're welcome.

Try this and let me know if it works. 

**Regarding Reactive Extensions**:. 
When Rx changed from version 2.2.5 to version 3.0.0 they changed the namespace. To ensure that the namespace change works corrently I will suggest that you remove all rx-xxxx nugets and also remove all the new System.Reactive nugets. After you are sure they are all gone add System.Reactive again. That should fix that issue.  

**Regarding SocketLite.PCL**
For Android (i.e. .NET) you need to make sure that SocketLite.PCL is referenced. As it says in the Readme: 

> IMPORTANT: SocketList.PCL utilizes the "Bait and Switch" pattern and the SocketLite.PCL nuget must be part of any project using Simple Http Listner PCL.

For Windows 10 (i.e UWP) you also need to make sure that SocketLite.PCL is referenced. Also, you need to ensure that Microsoft.NETCore.UniversalWindowsPlatform 5.2 is added. For some reasone Microsoft.NETCore.UniversalWindowsPlatform 5.2 is currently not a visible update. I'm sure it will be shortly, but it was there for a day and two and then it disappeared. I saw the same thing happen with version 5.1.

Anyhow, to add it just go to the Nuget Package Manager Console, make sure you choose your proejt in the Default project drop-down and run: 
`install-package Microsoft.NETCore.UniversalWindowsPlatform -Version 5.2`

**Comment by paulyfwu** [comment]
001) Regarding Reactive Extensions:
I did "PM>  Uninstall-Package System.Reactive.*" a few times (one of which with -Force option to ignore dependency by SimpleHttpListener itself.), and then followed by "PM> Install-Package System.Reactive" and successfully got back System.Reactive 3.0.0.

002) Regarding SocketLite.PCL:
I see that both "ISocketLite.PCL" (yes with the leading "I"), and "SocktLite" are part of the list of References (as viewed by Solution Explorer). But "SocketLite.PCL" is not in the same References list.
I would love to add "SocketLite.PCL" to References but I am not clear how to do that manually.

003) Regarding the "System.Runtime.InteropServices.WindowsRuntime.dll" error:
Here is the original error message:

[[[
Severity	Code	Description	Project	File	Line	Suppression State

Error		Multiple assemblies with equivalent identity have been imported:
 
'C:\Users\xxxxx\Documents\xxxxx\xxxxx\packages\
System.Runtime.InteropServices.WindowsRuntime.4.0.1\lib\netstandard1.3\
System.Runtime.InteropServices.WindowsRuntime.dll' 

and 

'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\
System.Runtime.InteropServices.WindowsRuntime.dll'. 

Remove one of the duplicate references.	

xxxxx	C:\Users\PaulYF\Documents\xxxxx\xxxxx\xxxxx\CSC		

]]]

I think what I did to 'fix' this error was to manually remove the reference to "System.Runtime.InteropServices.WindowsRuntime.dll" in the project References list.
Perhaps that was a mistake ?????? (should I have removed the latter one (x86)...\MonoAndroid\... instead???, but I really do not know where that reference resides because it was/is not in the References list)

Thanks again for your attention. Paul

As it stands right now, after my actions on item 001, it is still behaving the same way as before.
That is, the test runs on the HTC Android 4.4.2, with no crashes but ""await httpListener.StartTcpRequestListener(port: 8000);"" does NOT complete or return.

**Comment by 1iveowl** [comment]
Regarding 001) You need to uninstall both System.Reative.* AND Rx-*. The first is version 3.0.0 and the second is version 2.2.5. 

Regarding 002) SocketLite.PCL must be in all your projects - assuming that you have multiple projects?

Regarding 003) No removing the reference is not a good idea. The issue here is that there are more that one assemblies that include this namespace. Removing the reference will remove the error, but only because there are now no reference to it and that will not work. The work-around I provided to you remove one of the assemblies, but maintained the reference. 

----

Paul, things are getting a bit messy now, with multiple new issues arising from the current state and the changes you've made. Could you please try and: 

a) clone the code I've provided here and see if you can run Console.Net.Test. If you can run that on your PC, you should also be able to run it with an Android project. 

b) Try and create a new project and start from a fresh and move you other code to this new project?

**Comment by paulyfwu** [comment]
Dear 1iveowl, 
You are absolutely right, I was making it too complicated in trying to run before I could even crawl.
So I went back to the basics and just downloaded your sample test projects, going into Console.Net.Test, refreshed all packages, and was able to have the first successful run, resulting in seeing "Hello, World! 7/11/2016 5:45:09 PM" in a web browser page.
One catch is that (as I suspected) I needed to launch VS2015 in Administrator mode (for the privileged operation of HTTP listening on a port.)

Now I am ready to test it on Android and iOS, but the "......\Simple-Http-Listener-PCL-master\src\SimpleHttpServer\Tests" folder is missing the "Android.Text" (yes, "*.Text") and "iOS.Test" projects that used to exist in the 8July zip file that I had downloaded earlier.
That is, the latest zip file is missing those two Tests.
To prevent any accidental misinterpretation of the dependencies, could you re-insert those two platform Tests, for my benefit.
Thanks again and this is great progress. Paul
ps. Your patience with me is highly appreciated.

**Comment by 1iveowl** [comment]
You are welcome and thanks for providing input that made the readme better.

I removed the Android and iOS test because they where not doing anything. Trust me, you don't need them.

Now that we have verified that it does indeed work, I will advice you to create an all new project and add the SimpleHttpListener Nuget as needed and the SocketLite.PCL to any additional projects in your solution and work from there. 

I've not run into any issues with Administrator rights, but maybe that is because my user is an administrator alreadt.

**Comment by paulyfwu** [comment]
Just an FYI update on Android, after proving that it works on Console.Net.Test already.

I created a fresh and blank Android Project named 'Droid2Listen', Installed 'SimpleHttpListener' Nuget package within the project, and cloned all the necessary httpListener codes into it. Upon build, the OLD error came back, whose message is listed below as delimited by [[[ ... ]]].

So it appears that the SimpleHttpListener package is depending on a newer (or maybe just different) version of WindowsRuntime.DLL than the "default" WindowsRunTime? Thanks, Paul

[[[
Severity	Code	Description	Project	File	Line	Suppression State

Error		Multiple assemblies with equivalent identity have been imported: 

'C:\Users\xxx\Documents\yyy\exp2_simpleHttpListen
\Simple-Http-Listener-PCL-master\src\SimpleHttpServer\packages
\System.Runtime.InteropServices.WindowsRuntime.4.0.1\lib\netstandard1.3
\System.Runtime.InteropServices.WindowsRuntime.dll' 

and 

'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades
\System.Runtime.InteropServices.WindowsRuntime.dll'. 

Remove one of the duplicate references.	

Droid2Listen	
C:\Users\xxx\Documents\yyy\exp2_simpleHttpListen
\Simple-Http-Listener-PCL-master\src\SimpleHttpServer\Tests\Droid2Listen\CSC
]]]

**Comment by 1iveowl** [comment]
The issue with:

> Error Multiple assemblies with equivalent identity have been imported

This is unrelated to SimpleHttpListener. It is an issue with Xamarin/Android and Visual Studio 2015 Update 3 I believe. Others are seeing the same thing: [From Xamarin Forum](https://forums.xamarin.com/discussion/70413/i-am-getting-a-multiple-assemblies-with-equivalent-identity-have-been-imported-error)

I have described to you earlier how to deal with this issue.  

> Regarding the "System.Runtime.InteropServices.WindowsRuntime.dll" error
>  When did you encounter this error? I've seen it as I was updating to VS2015 Update 3. The way I fixed this was to go into the  .csproj  file and comment out the reference like this:
> 
> ```xml
> 
> ```
> 

I hope this helps?

**Comment by paulyfwu** [comment]
Thanks, I finally understood your previous advice. So I did the commenting out of the Reference section.
So now it builds and deploys. When running, unexpectedly it ran into multiple DLL NOT FOUND errors, as examples shown below. So I am at the point of giving it all up. Thanks for all your guidance though. Cheers - Paul

====================
07-13 17:26:07.352 D/Mono    (30655): Image addref mscorlib[0x725ad108] -> mscorlib.dll[0x725ac418]: 1
07-13 17:26:07.362 D/Mono    (30655): AOT module 'mscorlib.dll.so' not found: dlopen failed: library "/data/app-lib/Droid2Listen.Droid2Listen-1/libaot-mscorlib.dll.so" not found
07-13 17:26:07.362 D/Mono    (30655): AOT module '/Users/builder/data/lanes/3053/a94a03b5/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/mscorlib.dll.so' not found: dlopen failed: library "/data/app-lib/Droid2Listen.Droid2Listen-1/libaot-mscorlib.dll.so" not found
07-13 17:26:07.372 D/Mono    (30655): Unloading image data-0x725ae008 [0x725ad188].
07-13 17:26:07.432 D/Mono    (30655): Assembly mscorlib[0x725ad108] added to domain RootDomain, ref_count=1
07-13 17:26:07.492 D/Mono    (30655): Image addref Droid2Listen[0x727f3328] -> Droid2Listen.dll[0x727ee7c0]: 1
07-13 17:26:07.492 D/Mono    (30655): Assembly Droid2Listen[0x727f3328] added to domain RootDomain, ref_count=1
07-13 17:26:07.502 D/Mono    (30655): AOT module 'Droid2Listen.dll.so' not found: dlopen failed: library "/data/app-lib/Droid2Listen.Droid2Listen-1/libaot-Droid2Listen.dll.so" not found
07-13 17:26:07.502 D/Mono    (30655): AOT module '/Users/builder/data/lanes/3053/a94a03b5/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/Droid2Listen.dll.so' not found: dlopen failed: library "/data/app-lib/Droid2Listen.Droid2Listen-1/libaot-Droid2Listen.dll.so" not found
07-13 17:26:07.502 D/Mono    (30655): Unloading image data-0x727f33d8 [0x727f3eb8].
07-13 17:26:07.502 D/Mono    (30655): Image addref HttpMachine[0x727f4c78] -> HttpMachine.dll[0x727f4020]: 1
07-13 17:26:07.502 D/Mono    (30655): Assembly HttpMachine[0x727f4c78] added to domain RootDomain, ref_count=1
07-13 17:26:07.502 D/Mono    (30655): AOT module 'HttpMachine.dll.so' not found: dlopen failed: library "/data/app-lib/Droid2Listen.Droid2Listen-1/libaot-HttpMachine.dll.so" not found
07-13 17:26:07.502 D/Mono    (30655): AOT module '/Users/builder/data/lanes/3053/a94a03b5/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/HttpMachine.dll.so' not found: dlopen failed: library "/data/app-lib/Droid2Listen.Droid2Listen-1/libaot-HttpMachine.dll.so" not found

...
Unhandled Exception:

System.TypeInitializationException: The type initializer for 'System.Reactive.Linq.Observable' threw an exception.

**Comment by paulyfwu** [comment]
Just to be complete, note that my other Android Apps are still loading and running (either debug mode or just plainly running on the phone standalone) fine. (in contrast to the Droid2Listen project having lots of DLLs not loading properly), Cheers, Paul

**Comment by 1iveowl** [comment]
This is weird.

Are you sure that you are running the latest version of Xamarin?
